### ISSUE TITLE
doc/ folder management

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#462]
See: https://github.com/embedded-graphics/embedded-graphics/pull/459#discussion_r518289665

We need a way to update the `doc/` folder.

**Comment by rfuest** [comment]
I just ran into this issue when I tried to update the `simulator` dependencies. The `generate-drawing-examples` binary requires a dependency to `tinytga`, so that the simulator crate must have a `dependency` on `tinytga` and cannot use a `dev-dependency`.

Should we move the code for the `generate-drawing-examples` binary into the `build-tools` repo? If we do that we would need to also clone the `build-tools` repo during builds of this repo, to check if the examples in the doc folder are up to date.

**Comment by jamwaffles** [comment]
It would make sense to move them into `build-tools`, yes. It's a public repository so I don't think cloning it in CI is a problem. (I've had lots of issues in the past cloning private repos)

**Comment by rfuest** [comment]
Another option would be to add a separate crate for the examples generator to the `embedded-graphics` repo, that is not part of the workspace. IMO this would be better, because we could keep everything in one repo and it shouldn't mess with any dependencies when it's not even part of the workspace.

We should also change the tool to output markdown directly, instead of having to use `sed` in the `justfile`. This would bring us one step closer to being able to run `just build` on Windows.
